---
# tasks file for dns

# subscription-manager refresh
  - name: Refresh subscription manager
    command: subscription-manager refresh 


# yum install install bind bind-utils

  - name: Install the latest of bind bind-utils
    ansible.builtin.yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - bind
      - bind-utils
      
      
# systemctl enable named -(enable the DNS)
# service named start

  - name: named started enabled
    service:
      name: named
      state: started

  - name: named 
    service:
      name: named
      enabled: yes

  - name: Remove file /etc/named.conf
    ansible.builtin.file:
      path: /etc/named.conf
      state: absent


  - name: adding foward zone and back zone to named.conf
    ansible.builtin.blockinfile:
      insertafter: EOF
      create: yes
      marker: "// from ansible"
      path: /etc/named.conf
      block: |
        //
        // named.conf
        //
        // Provided by Red Hat bind package to configure the ISC BIND named(8) DNS
        // server as a caching only nameserver (as a localhost DNS resolver only).
        //
        // See /usr/share/doc/bind*/sample/ for example named configuration files.
        //
        // See the BIND Administrator's Reference Manual (ARM) for details about the
        // configuration located in /usr/share/doc/bind-{version}/Bv9ARM.html

        options {
        //      listen-on port 53 { 127.0.0.1; };
        //      listen-on-v6 port 53 { ::1; };
                directory       "/var/named";
                dump-file       "/var/named/data/cache_dump.db";
                statistics-file "/var/named/data/named_stats.txt";
                memstatistics-file "/var/named/data/named_mem_stats.txt";
                recursing-file  "/var/named/data/named.recursing";
                secroots-file   "/var/named/data/named.secroots";
                allow-query     { localhost; {{ subnet }}/24; };

                /*
                - If you are building an AUTHORITATIVE DNS server, do NOT enable recursion.
                - If you are building a RECURSIVE (caching) DNS server, you need to enable
                  recursion.
                - If your recursive DNS server has a public IP address, you MUST enable access
                  control to limit queries to your legitimate users. Failing to do so will
                  cause your server to become part of large scale DNS amplification
                  attacks. Implementing BCP38 within your network would greatly
                  reduce such attack surface
                */
                recursion yes;

                dnssec-enable yes;
                dnssec-validation yes;

                /* Path to ISC DLV key */
                bindkeys-file "/etc/named.root.key";

                managed-keys-directory "/var/named/dynamic";

                pid-file "/run/named/named.pid";
                session-keyfile "/run/named/session.key";

        };

        logging {
                channel default_debug {
                        file "data/named.run";
                        severity dynamic;
                };
        };

        zone "." IN {
                type hint;
                file "named.ca";
        };


        include "/etc/named.rfc1912.zones";
        include "/etc/named.root.key";

        //foward zone
        zone "{{ domain_name }}.{{ domain_name_extension }}" IN {
                type master;
                file "{{ domain_name }}.{{ domain_name_extension }}.db";
                allow-update { none; };
                allow-query { any; };
        };
        //back zone
        zone "{{ back_zone }}.in-addr.arpa" IN {
                type master;
                file "{{ domain_name }}.{{ domain_name_extension }}.rev";
                allow-update { none; };
                allow-query { any; };
        };



# # edit /var/named/{{ domainName }}.co.uk.db  -(Create the forward zone file with hostnames )   

# #  (will use domain name for file name)


  - name: "writting the file /var/named/{{ domain_name }}.{{ domain_name_extension }}.db"
    blockinfile:
      dest: /var/named/{{ domain_name }}.{{ domain_name_extension }}.db
      insertafter: EOF
      marker: ";from ansible"
      create: yes
      block: |
        $TTL 86400
        @ IN SOA dns-primary.{{ domain_name }}.{{ domain_name_extension }}. admin.{{ domain_name }}.{{ domain_name_extension }}. (
            2019061800 ;Serial
            3600 ;Refresh
            1800 ;Retry
            604800 ;Expire
            86400 ;Minimum TTL
        )

        ;Name Server Information
        @ IN NS dns-primary.{{ domain_name }}.{{ domain_name_extension }}.

        ;IP for Name Server
        dns-primary IN A {{ data[3].ip }}

        ;A Record for IP address to Hostname 

  - name: "making test file"
    lineinfile:
      dest: "/var/named/{{ domain_name }}.{{ domain_name_extension }}.db"
      insertafter: EOF
      marker: ";from ansible"
      line: "{{ data[my_idx].name }} IN A {{ data[my_idx].ip }}"
    loop:
     "{{ data }}"
    loop_control:
      index_var: my_idx

  - name: "writting the file /var/named/{{ domain_name }}.{{ domain_name_extension }}.rev"
    blockinfile:
      dest: /var/named/{{ domain_name }}.{{ domain_name_extension }}.rev
      insertafter: EOF
      marker: ";from ansible"
      create: yes
      block: |
        $TTL 86400
        @ IN SOA dns-primary.{{ domain_name }}.{{ domain_name_extension }}. admin.{{ domain_name }}.{{ domain_name_extension }}. (
            2019061800 ;Serial
            3600 ;Refresh
            1800 ;Retry
            604800 ;Expire
            86400 ;Minimum TTL
        )
        ;Name Server Information
        @ IN NS dns-primary.{{ domain_name }}.{{ domain_name_extension }}.

        ;Reverse lookup for Name Server
        3 IN PTR dns-primary.{{ domain_name }}.{{ domain_name_extension }}.

        ;PTR Record IP address to HostName
        2 IN PTR dhcp.{{ domain_name }}.{{ domain_name_extension }}.
        1 IN PTR gateway.{{ domain_name }}.{{ domain_name_extension }}.


  - name: Change file ownership to named for db
    ansible.builtin.file:
      path: /var/named/{{ domain_name }}.{{ domain_name_extension }}.db 
      group: named 

  # - name: Allow named to have access to {{ domain_name }}.{{ domain_name_extension }}.db
  #   command: chown :named /var/named/{{ domain_name }}.{{ domain_name_extension }}.db


  - name: Change file ownership to named for db
    ansible.builtin.file:
      path: /var/named/{{ domain_name }}.{{ domain_name_extension }}.rev 
      group: named 

  # - name: Allow named to have access to {{ domain_name }}.{{ domain_name_extension }}.rev
  #   command: chown :named /var/named/{{ domain_name }}.{{ domain_name_extension }}.rev


  - name: named-checkconf
    command: named-checkconf


  - name: add domain .db files to the named-checkzone
    command: named-checkzone {{ domain_name }}.{{ domain_name_extension }} /var/named/{{ domain_name }}.{{ domain_name_extension }}.db

  - name: add domain .rev files to the named-checkzone
    command: named-checkzone {{ data[3].ip }} /var/named/{{ domain_name }}.{{ domain_name_extension }}.rev



# # restart named 

  - name: reloading named
    service:
      name: named
      state: restarted

 

# # add dns to fire wall

# firewall-cmd  --add-service=dns --zone=public  --permanentfirewall-cmd --reload

  - name: permit traffic in default zone for dns service
    ansible.posix.firewalld:
      service: dns
      permanent: yes
      state: enabled


# # edit /etc/sysconfig/network-scripts/ifcfg-ens224

# # "DNS1=10.0.0.3" 

  - name: Editing network service
    blockinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-{{ data[3].interface_in_name }}
      block: |
        DEFROUTE=yes
        GATEWAY={{ data[0].ip}}
        DOMAIN={{ domain_name }}.{{ domain_name_extension }}
        DNS1={{ data[3].ip }}
      insertafter: EOF

# # restart network

  - name: reloading network
    service:
      name: network
      state: restarted


  - name: "Removing {{ dns_interface_out_name }}"
    community.general.nmcli:
      conn_name: "{{ dns_interface_out_name }}"
      state: absent

    